from numpy import nan as nan

# key: what SRA says
# value: [scientific name, scientific name certainty (1-3, 3 is highest), common name]
species = {
	'African Elephant': ['Loxodonta sp.', 3, "African elephant"],
	'Antelope Cervicapra': ['Antilope cervicapra', 3, "blackbuck"],
	'antelope': [nan, 3, "antelope"],
	'antelope zoo': [nan, 3, "antelope"],
	'antilope zoo': [nan, 3, "antelope"],
	'Antilope cervicapra blackbuck': ['Antilope cervicapra', 3, "blackbuck"],
	'Axis axis': ['Axis axis', 3, "chital deer"],

	'BADGER': ['Meles meles', 1, "badger"],
	'Badger': ['Meles meles', 1, "badger"],
	'Bison': ['Bison sp.', 2, "bison"],
	'Bison bison athabascae': ['Bison bison athabascae', 3, "wood bison"],
	'Bison bison athabascae wood bison': ['Bison bison athabascae', 3, "wood bison"],
	'Bison bonasus': ['Bison bonasus', 3, "European bison"],
	'Bison bonasus European bison': ['Bison bonasus', 3, "European bison"],
	'Body organs': [nan, 1, nan], # many of these seem to be PRJNA643892 which is 'multispecies'
	'Bobcat': ['Lynx rufus', 2, "bobcat"],
	'Bos gaurus': ['Bos gaurus', 3, "guar"],
	'Bos taurus': ['Bos taurus', 3, "domestic cattle"],
	'Bos taurus domestic cattle': ['Bos taurus', 3, "domestic cattle"],
	'Bos taurus (presumed)': ['Bos taurus', 2, "domestic cattle"],
	'bovine': ['Bos taurus', 2, "bovine"],
	'Bovine': ['Bos taurus', 2, "bovine"],
	'BOVINE': ['Bos taurus', 2, "bovine"],
	'Buffalo': [nan, 3, "buffalo"],
	'Bubalus bubalis': ['Bubalus bubalis', 3, "water buffalo"],
	'Boar': ['Sus scrofa', 2, "wild boar"],
	
	'canid': ['Canis sp.', 2, "canine"], # canine = canid
	'canine': ['Canis sp.', 2, "canine"],
	'Canis': ['Canis sp.', 3, "canine"],
	'Canis lupus familiaris': ['Canis lupus familiaris', 3, "domestic dog"],
	'Canis lupus familiaris,': ['Canis lupus familiaris', 3, "domestic dog"],
	'Canis lupus familiaris domestic dog': ['Canis lupus familiaris', 3, "domestic dog"],
	'Capra hircus': ['Capra hircus', 3, "domestic goat"],
	'Capreolus capreolus': ['Capreolus capreolus', 3, "roe deer"],
	'Cattle:Beef': ['Bos taurus', 2, "domestic cattle"],
	'Cattle:Dairy': ['Bos taurus', 2, "domestic cattle"],
	'Cattle': ['Bos taurus', 2, "domestic cattle"],
	'cattle': ['Bos taurus', 2, "domestic cattle"],
	'Cervid': [nan, 2, "deer"],
	'CERVINE': [nan, 2, "deer"],
	'Cervine': [nan, 2, "deer"],
	'Cervus elaphus': ['Cervus elaphus', 3, "red deer"],
	'cow': ['Bos taurus', 2, "domestic cattle"],
	'Cow': ['Bos taurus', 2, "domestic cattle"],
	'COW': ['Bos taurus', 2, "domestic cattle"],
	'Coyote': ['Canis latrans', 3, "coyote"],
	'Culture': [nan, 1, nan],
	
	'Dama dama': ['Dama dama', 3, "fallow deer"],
	'Dassie': ['Procavia capensis', 3, "dassie"],
	'DEER': [nan, 3, "deer"],
	'Deer': [nan, 3, "deer"],
	'deer': [nan, 3, "deer"],
	'Deer Unknown': [nan, 3, "deer"],
	'Didelphis virginiana': ['Didelphis virginiana', 3, "Virgina opossum"],
	'Didelphis virginiana Virgina opossum': ['Didelphis virginiana', 3, "Virgina opossum"],
	'dog': ['Canis lupus familiaris', 2, "domestic dog"],
	
	'Elephas maximus': ['Elephas maximus', 3, "Asian elephant"],
	'Elephas maximus Asian elephant': ['Elephas maximus', 3, "Asian elephant"],
	'Elk': [nan, 3, "elk"],
	'elk': [nan, 3, "elk"],
	'Elephant': [nan, 3, "elephant"],
	
	'Feline': '"feline"', # likely domestic cats since it's just NZ so far
	'Feline': '"feline"',
	'feline': '"feline"',
	'Felis catus': ['Felis catus', 3, "domestic cat"],
	'Felis catus domestic cat': ['Felis catus', 3, "domestic cat"],
	'FERRET': ['Mustela sp.', 2, "ferret"], # could be domestic, could be black-footed
	'Ferret':  ['Mustela sp.', 2, "ferret"], # could be domestic, could be black-footed
	'Fox': [nan, 3, "fox"],
	'fox': [nan, 3, "fox"],
	
	'Goat': ['Capra hircus', 3, "domestic goat"],
	
	'Hedgehog': [nan, 3, "hedgehog"],
	'hedgehog': [nan, 3, "hedgehog"],
	'Homo sapiens': ['Homo sapiens', 3, "human"],
	'Homo sapiens NCBI:': ['Homo sapiens', 3, "human"],
	'Homo sapiens sapiens': ['Homo sapiens', 3, "human"],
	'Homo sapiens human': ['Homo sapiens', 3, "human"],
	'Human, Homo sapiens': ['Homo sapiens', 3, "human"],
	'Human': ['Homo sapiens', 3, "human"],
	'Human host': ['Homo sapiens', 3, "human"],
	'human': ['Homo sapiens', 3, "human"],
	'human patient': ['Homo sapiens', 3, "human"],
	'Human/Culture': [nan, 1, nan],
	'Hydrochoerus hydrochaeris': ['Hydrochoerus hydrochaeris', 3, "capybara"],
	'Hydrochoerus hydrochaeris capybara': ['Hydrochoerus hydrochaeris', 3, "capybara"],
	
	'Jaguar': ['Panthera onca', 3, "jaguar"],

	'Kobus ellipsiprymnus': ['Kobus ellipsiprymnus', 3, "waterbuck"],
	'Kobus ellipsiprymnus waterbuck': ['Kobus ellipsiprymnus', 3, "waterbuck"],
	
	'Laboratory': [nan, 2, 'lab strain'],
	'laboratory': [nan, 2, 'lab strain'],
	'Lab strain': [nan, 2, 'lab strain'],
	'Lama glama': ['Lama glama', 3, "llama"],
	'Loxodonta': ['Loxodonta sp.', 2,"African elephant"],
	'Lutra lutra': ['Lutra lutra', 3, "Eurasian otter"],
	'Lycaon pictus': ['Lycaon pictus', 3, "African wild dog"],
	
	'Macaca fascicularis': ['Macaca fascicularis', 3, "crab-eating macaque"],
	'Meles meles': ['Meles meles', 3, "European badger"],
	'mouse': ['Mus musculus', 2, "mouse"],
	'Mouse': ['Mus musculus', 2, "mouse"],
	'Mungos mungo': ['Mungos mungo', 3, "banded mongoose"],
	'Monkey': '"monkey"',
	'Monkey, Cynomolgus': ['Macaca fascicularis', 2, "crab-eating macaque"],
	'Mus musculus': ['Mus musculus', 3, "mouse"],
	'Mus musculus mouse': ['Mus musculus', 3, "mouse"],
	'Mustela sp.': ['Mustela sp.', 2, "ferret"],
	'Mustela sp. ferret': ['Mustela sp.', 2, "ferret"],
	'Mustela erminea': ['Mustela erminea', 3, "stoat"],
	'Mycobacterium tuberculosis': [nan, 1, nan],
	
	'NAN': [nan, 1, nan],
	'non human primate': [nan, 3, "non-human primate"],
	'non-human primate': [nan, 3, "non-human primate"],
	
	'Opossum': ['Didelphis virginiana', 1, "opossum"], # there are other species but they usually aren't just called "opossum"
	'Otaria byronia': ['Otaria byronia', 3, "South American sea lion"],
	'Oryx zoo': ['Oryx sp.', 2, "oryx"],
	'Oryx sp. oryx': ['Oryx sp.', 2, "oryx"],
	'Ovis aries': ['Ovis aries', 3, "domestic sheep"],
	'Ovis aries domestic sheep': ['Ovis aries', 3, "domestic sheep"],
	
	'Pan troglodytes': ['Pan troglodytes', 3, "chimpanzee"],
	'Panthera leo': ['Panthera leo', 3, "lion"],
	'Panthera onca': ['Panthera onca', 3, "jaguar"],
	'Panthera pardus': ['Panthera pardus', 3, "leopard"],
	'Papio sp.': ['Papio sp.', 2, "baboon"],
	'Primate': [nan, 2, "non-human primate"],
	'primate': [nan, 2, "non-human primate"],
	'PORCINE': ['Sus scrofa', 1, "wild boar or pig"],
	'POSSUM': [nan, 2, 'possum'], # not the same as opossum
	'Possum': [nan, 2, 'possum'], # not the same as opossum
	'Pig': ['Sus scrofa domesticus', 2, "domestic pig"],
	'Procavia capensis': ['Procavia capensis', 3, "dassie"],
	'Propithecus coquereli': ['Propithecus coquereli', 3, "Coquerel`s sifaka"],
	'Procyon sp.': ['Procyon sp.', 2, "raccoon"],
	
	'Raccoon': ['Procyon sp.', 2, "raccoon"],
	'Racoon': ['Procyon sp.', 2, "raccoon"],
	'Red Deer': ['Cervus elaphus', 2, "red deer"],
	'Red deer': ['Cervus elaphus', 2, "red deer"],
	'Red fox': ['Vulpes vulpes', 2, "red fox"],
	'Rhino': [nan, 3, "rhinoceros"],
	'rhinoceros': [nan, 3, "rhinoceros"],
	
	'sea lion': [nan, 3, "sea lion"],
	'Sheep': ['Ovis aries', 2, "domestic sheep"],
	'STOAT': ['Mustela erminea', 2, "stoat"],
	'Stoat': ['Mustela erminea', 2, "stoat"],
	'Suricat': ['Suricata suricatta', 2, "meerkat"],
	'Sus scrofa': ['Sus scrofa', 2, "wild boar or pig"],
	'Sus scrofa domesticus': ['Sus scrofa domesticus', 3, "domestic pig"],
	'Syncerus caffer': ['Syncerus caffer', 3, "African buffalo"],
	
	'Tissue: Lymph nodes': [nan, 1, nan],
	'Tragelaphus strepsiceros': ['Tragelaphus strepsiceros', 3, "greater kudu"],
	'Tragelaphus strepsiceros greater kudu': ['Tragelaphus strepsiceros', 3, "greater kudu"],
	'Tuberculosis': [nan, 1, nan],
	
	'Varecia variegata subcincta': ['Varecia variegata subcincta', 3, "white-belted black-and-white ruffed lemur"],
	'Vulpes vulpes': ['Vulpes vulpes', 3, "red fox"],
	'Vulpes vulpes red fox': ['Vulpes vulpes', 3, "red fox"],
	
	'waterbuck zoo': ['Kobus ellipsiprymnus', 3, "waterbuck"],
	'Wild Boar': ['Sus scrofa', 2, "wild boar"],
	'Wild boar': ['Sus scrofa', 2, "wild boar"],
	'wild boar': ['Sus scrofa', 2, "wild boar"],
}